- pipeline.id: syslog
  path.config: "/usr/share/logstash/pipeline/syslog.conf"
- pipeline.id: beats
  path.config: "/usr/share/logstash/pipeline/beats.conf"
- pipeline.id: syslog_cisco
  path.config: "/usr/share/logstash/pipeline/syslog_cisco.conf"
- pipeline.id: syslog_mikrotik
  path.config: "/usr/share/logstash/pipeline/syslog_mikrotik.conf"
- pipeline.id: kafka
  path.config: "/usr/share/logstash/pipeline/kafka.conf"
- pipeline.id: beats_5045
  path.config: "/usr/share/logstash/pipeline/beats_5045.conf"
- pipeline.id: winlogbeats_5046
  path.config: "/usr/share/logstash/pipeline/winlogbeats_5046.conf"
- pipeline.id: auditbeats_5047
  path.config: "/usr/share/logstash/pipeline/auditbeats_5047.conf"
- pipeline.id: netflow_filebeat_5048
  path.config: "/usr/share/logstash/pipeline/netflow_filebeat_5048.conf"
- pipeline.id: filebeat_5049
  path.config: "/usr/share/logstash/pipeline/filebeat_5049.conf"
